coverage:
  range: 70..100
  round: down
  precision: 2
  status:
    project:
      default: false  # disable the default status that measures entire project
      unittests:  # declare a new status context "unittests"
        target: 95%  # we always want 95% coverage here excluding some paths
        flags:
          - all
flags:
  unittests:
    paths:
      - "!cartesio/core/exceptions.py"
      - "!cartesio/core/jit_compile.py"

