name: coverage

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version  }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate coverage report
      env:
        CARTESIO_DISABLE_JIT_COMPILE: TRUE
      run: |
        pip install coverage
        coverage run -m unittest discover -s tests
        coverage xml
        coverage report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON,CARTESIO_DISABLE_JIT_COMPILE
        name: codecov-cartesio
        fail_ci_if_error: false